export const marketingStyles = {
  page: "min-h-screen bg-[#050505] text-zinc-100 py-32 px-6 relative overflow-hidden",
  pageAlt: "min-h-screen bg-[#050505] text-zinc-100 py-32 px-6 overflow-hidden relative",
  decorTop: "absolute top-0 right-0 w-[600px] h-[600px] bg-studio/5 blur-[180px] rounded-full pointer-events-none",
  decorBottom: "absolute bottom-0 left-0 w-[600px] h-[600px] bg-fuchsia-500/5 blur-[180px] rounded-full pointer-events-none",
  wrapper: "max-w-7xl mx-auto space-y-24 relative z-10",
  sectionHeader: "flex flex-col items-center text-center space-y-8",
  badgePill: "flex items-center gap-3 px-4 py-1.5 rounded-full bg-studio/5 border border-studio/20",
  badgeText: "text-[10px] font-black uppercase tracking-[0.4em] text-studio",
  pageTitle: "text-5xl md:text-8xl font-black text-white uppercase italic tracking-tighter leading-none",
  pageTitleAccent: "text-studio",
  pageDescription: "max-w-2xl mx-auto text-zinc-500 font-bold uppercase tracking-[0.2em] text-[11px] leading-relaxed",
  helpLoadingRoot: "min-h-screen bg-[#050505] flex flex-col items-center justify-center space-y-6",
  helpLoadingSpinnerWrapper: "relative",
  helpLoadingSpinner: "w-16 h-16 border-2 border-studio/20 border-t-studio rounded-full animate-spin",
  helpLoadingIconWrapper: "absolute inset-0 flex items-center justify-center",
  helpLoadingLabel: "text-[10px] font-black text-studio uppercase tracking-[0.5em] animate-pulse",
  helpIntroStack: "space-y-6",
  helpSearchSurface: "w-full max-w-3xl relative group",
  helpSearchFocusRing: "absolute -inset-1 bg-gradient-to-r from-studio/30 to-fuchsia-500/30 rounded-[2.5rem] blur-xl opacity-0 group-focus-within:opacity-100 transition duration-700",
  helpFaqGrid: "grid grid-cols-1 gap-6",
  helpFaqCard: "p-8 bg-[#0a0a0b] border border-white/5 rounded-[2.5rem] hover:border-studio/30 transition-all cursor-pointer group shadow-xl",
  helpFaqContent: "flex items-start justify-between gap-8",
  helpFaqMeta: "space-y-4",
  helpFaqRow: "flex items-center gap-3",
  helpFaqDot: "w-1.5 h-1.5 rounded-full bg-studio",
  helpFaqQuestion: "text-[11px] font-black text-white uppercase tracking-widest group-hover:text-studio transition-colors",
  helpFaqAnswer: "text-[11px] text-zinc-500 font-bold uppercase tracking-widest leading-relaxed pl-4 border-l border-white/5",
  helpFaqLink: "bg-zinc-900 p-2.5 rounded-xl text-zinc-700 group-hover:text-studio group-hover:bg-white transition-all shadow-inner",
  helpNoResultsCard: "text-center py-32 bg-zinc-900/10 rounded-[3rem] border border-dashed border-white/5",
  helpNoResultsIcon: "w-16 h-16 text-zinc-800 mx-auto mb-6 animate-spin-slow",
  helpNoResultsText: "text-zinc-600 font-black uppercase tracking-[0.4em] text-[10px]",
  helpContentGrid: "grid grid-cols-1 lg:grid-cols-12 gap-16",
  helpContentColumn: "lg:col-span-8 space-y-10",
  helpSidebarColumn: "lg:col-span-4 space-y-10",
  helpPanelHeader: "flex items-center justify-between border-b border-white/5 pb-8",
  helpPanelBadgeRow: "flex items-center gap-4",
  helpPanelBadge: "p-2.5 bg-studio/10 rounded-xl border border-studio/20",
  helpPanelIcon: "w-6 h-6 text-studio fill-studio",
  helpPanelHeading: "text-3xl font-black text-white uppercase italic tracking-tighter",
  resetButton: "text-[10px] font-black text-zinc-600 hover:text-white uppercase tracking-widest transition-colors",
  helpCardPanel: "bg-gradient-to-br from-[#0a0a0b] to-black border border-white/5 p-10 rounded-[3rem] space-y-8 shadow-3xl",
  helpCardBody: "space-y-4 text-center",
  helpCardIconWrap: "w-20 h-20 bg-studio/5 rounded-3xl flex items-center justify-center mx-auto mb-6 border border-studio/10 relative",
  helpSupportCardIcon: "w-8 h-8 group-hover:text-black transition-colors",
  helpCallToActionButton: "w-full h-16 bg-studio text-black font-black uppercase tracking-[0.3em] text-[11px] rounded-[1.5rem] hover:bg-white transition-all shadow-2xl",
  helpSidebarStack: "space-y-6",
  helpSidebarLinks: "grid grid-cols-1 gap-3",
  helpSidebarLink: "flex items-center justify-between p-6 bg-zinc-900/30 border border-white/5 rounded-[1.5rem] hover:bg-studio/5 hover:border-studio/30 transition-all group no-underline",
  helpSidebarLinkContent: "flex items-center gap-4",
  helpSidebarLinkText: "text-[10px] font-black text-zinc-500 uppercase tracking-[0.3em] group-hover:text-white",
  helpSidebarLinkIcon: "w-4 h-4 text-zinc-800 group-hover:text-studio",
  footerLinks: "flex items-center gap-12",
  footerLink: "hover:text-studio transition-colors no-underline",
  helpLoadingIcon: "w-6 h-6 text-studio animate-pulse",
  helpIntroRow: "flex items-center justify-center gap-3",
  helpHighlight: "text-studio",
  helpBadgeIcon: "w-3.5 h-3.5 text-studio",
  helpCategoryRow: "flex items-center gap-4",
  helpCategoryId: "text-[9px] font-black text-zinc-700 uppercase tracking-[0.4em]",
  helpCategorySub: "text-[10px] text-zinc-500 font-bold uppercase tracking-widest mt-1",
  helpProtocolAction: "flex items-center gap-2 text-[9px] font-black text-studio uppercase tracking-[0.3em] opacity-0 group-hover:opacity-100 -translate-x-2 group-hover:translate-x-0 transition-all duration-700",
  helpSupportHeader: "flex items-center gap-4 border-b border-white/5 pb-8",
  helpSupportTag: "p-2.5 bg-fuchsia-500/10 rounded-xl border border-fuchsia-500/20",
  helpSupportBadgeIcon: "w-6 h-6 text-fuchsia-500",
  helpSupportTitle: "text-2xl font-black text-white uppercase italic tracking-tighter",
  helpSupportCopy: "text-[10px] text-zinc-600 font-black uppercase tracking-[0.2em]",
  externalLinkIcon: "w-4 h-4",
  helpFooterStatusDot: "w-1.5 h-1.5 bg-emerald-500 rounded-full animate-pulse shadow-[0_0_8px_rgba(16,185,129,0.5)]",
  footerRow: "flex items-center gap-6",
  footerMeta: "flex items-center gap-3",
  helpCardIconLarge: "w-10 h-10 text-studio",
  helpNotificationDot: "absolute -top-1 -right-1 w-4 h-4 bg-emerald-500 rounded-full border-4 border-black animate-pulse",
  footerDivider: "w-px h-4 bg-white/5 hidden md:block",
  termsBadge: "flex items-center gap-3 px-4 py-1.5 rounded-full bg-studio/5 border border-studio/20",
  termsBadgeIcon: "w-3.5 h-3.5 text-studio",
  termsBadgeText: "text-[10px] font-black text-studio uppercase tracking-[0.4em]",
  termsTitle: "text-5xl md:text-8xl font-black text-white uppercase italic tracking-tighter leading-none",
  termsTitleAccent: "text-studio",
  termsDescriptionText: "text-zinc-500 max-w-2xl uppercase text-[11px] font-bold tracking-[0.2em] leading-relaxed",
  termsGrid: "grid grid-cols-1 lg:grid-cols-12 gap-16",
  termsIndexSticky: "space-y-6 sticky top-32",
  termsIndexHeader: "flex items-center gap-4 border-b border-white/5 pb-8",
  termsIndexTitle: "text-2xl font-black text-white uppercase italic tracking-tighter",
  termsIndexList: "space-y-2",
  termsIndexLink: "flex items-center justify-between p-5 bg-zinc-900/30 border border-white/5 rounded-2xl hover:bg-studio/5 hover:border-studio/30 transition-all group no-underline",
  termsIndexMeta: "flex items-center gap-4",
  termsIndexRow: "flex items-center gap-4",
  termsIndexBadgeIcon: "w-6 h-6 text-studio fill-studio",
  termsIndexId: "text-[9px] font-black text-zinc-700 group-hover:text-studio transition-colors",
  termsIndexLabel: "text-[10px] font-black text-zinc-500 group-hover:text-white uppercase tracking-widest",
  termsIndexIcon: "w-4 h-4 text-zinc-800 group-hover:text-studio transition-colors",
  termsInfoCard: "p-8 rounded-[2rem] bg-fuchsia-500/[0.02] border border-fuchsia-500/10 space-y-4",
  termsInfoIcon: "w-5 h-5 text-fuchsia-500",
  termsContentColumn: "lg:col-span-8 space-y-12",
  termsSectionGroup: "space-y-4",
  termsSectionGroupLarge: "space-y-6",
  termsSectionIllustration: "w-32 h-32 text-studio",
  termsAcceptOverlay: "absolute inset-0 bg-gradient-to-br from-studio/5 via-transparent to-fuchsia-500/5",
  termsAcceptBadgeIcon: "w-6 h-6 fill-studio",
  buttonIcon: "ml-4 w-5 h-5",
  termsFooterRow: "flex items-center gap-6",
  termsFooterMeta: "flex items-center gap-3",
  termsFooterVerifiedIcon: "w-4 h-4 text-emerald-500",
  termsFooterDivider: "w-px h-4 bg-white/5 hidden md:block",
  termsInfoMeta: "flex items-center gap-3",
  termsInfoHeading: "text-[10px] font-black text-white uppercase tracking-widest",
  termsInfoText: "text-[10px] font-bold text-zinc-600 uppercase tracking-widest leading-relaxed",
  termsSectionDecor: "absolute top-0 right-0 p-10 opacity-5 group-hover:opacity-10 transition-opacity",
  termsSectionBlock: "space-y-6 relative z-10",
  termsSectionMeta: "flex items-center gap-4",
  termsSectionDot: "w-1.5 h-1.5 rounded-full bg-studio",
  termsSectionTag: "text-[10px] font-black text-studio uppercase tracking-[0.4em]",
  termsSectionHeading: "text-3xl md:text-5xl font-black text-white uppercase italic tracking-tighter",
  termsSectionCopy: "text-zinc-500 text-sm font-bold leading-relaxed uppercase tracking-widest",
  termsSubCard: "p-6 rounded-2xl bg-white/[0.02] border border-white/5",
  termsSubBadge: "text-[9px] font-black text-zinc-500 uppercase tracking-widest",
  termsSubText: "text-[10px] font-bold text-zinc-600 uppercase tracking-widest mt-2",
  policyGrid: "grid grid-cols-1 md:grid-cols-2 gap-4",
  policyItem: "flex items-center gap-3",
  policyDot: "w-2 h-2 rounded-full bg-red-500/20 border border-red-500/50",
  policyText: "text-[10px] font-black text-zinc-600 uppercase tracking-widest",
  termsAcceptCard: "p-12 md:p-20 rounded-[4rem] bg-studio/[0.03] border border-studio/20 text-center space-y-10 relative overflow-hidden group",
  termsAcceptHero: "flex flex-col items-center gap-4",
  termsAcceptBadge: "w-12 h-12 rounded-full bg-studio/10 border border-studio/20 flex items-center justify-center text-studio",
  termsAcceptTitle: "text-3xl md:text-5xl font-black text-white uppercase italic tracking-tighter",
  termsAcceptDescription: "text-zinc-500 text-[11px] font-bold uppercase tracking-[0.2em] max-w-xl mx-auto leading-relaxed",
  termsFooterLinks: "flex items-center gap-8",
  termsFooterLink: "hover:text-studio transition-colors no-underline",
  contactHeroIcon: "w-3.5 h-3.5 text-studio animate-pulse",
  contactConfirmedIcon: "w-5 h-5",
  contactSendIcon: "w-4 h-4",
  contactGlobeIcon: "w-4 h-4 text-studio",
  pricingBadgeWrapper: "absolute top-8 right-10",
  pricingBadgePill: "px-5 py-2 rounded-full bg-studio text-black text-[9px] font-black uppercase tracking-[0.2em] shadow-2xl flex items-center gap-2",
  pricingBadgeIcon: "w-3 h-3 fill-black",
  pricingCardHeader: "flex items-center justify-between mb-12",
  pricingCardTitle: "text-3xl font-black text-white uppercase italic tracking-tighter group-hover:text-studio transition-colors",
  pricingPriceRow: "flex items-baseline gap-2",
  pricingPriceValue: "text-5xl md:text-6xl font-black text-white italic tracking-tighter",
  pricingPriceSuffix: "text-zinc-600 font-black uppercase tracking-[0.3em] text-[10px]",
  pricingFeatureRow: "flex items-center gap-4 group/item",
  pricingFeatureIcon: "w-5 h-5 rounded-lg flex items-center justify-center transition-all duration-300",
  pricingFeatureIconHighlighted: "bg-studio/20 text-studio",
  pricingFeatureIconDefault: "bg-white/5 text-zinc-600 group-hover/item:bg-white/10",
  pricingFeatureText: "text-[11px] text-zinc-500 font-black uppercase tracking-widest group-hover/item:text-white transition-colors",
  pricingTelemetryRow: "mb-10 pt-8 border-t border-white/5 flex items-center justify-between",
  pricingTelemetryLabel: "space-y-1",
  pricingTelemetryTitle: "text-[8px] font-black text-zinc-700 uppercase tracking-widest",
  pricingTelemetryEfficiency: "text-[10px] font-black text-studio uppercase italic",
  pricingTelemetryIcon: "w-4 h-4 text-zinc-800",
  pricingButton: "h-16 rounded-[1.5rem] font-black uppercase tracking-[0.3em] text-[11px] transition-all relative overflow-hidden group/btn",
  pricingButtonHighlight: "bg-studio text-black hover:bg-white hover:scale-[1.02] shadow-3xl",
  pricingButtonDefault: "bg-white/5 text-white hover:bg-white hover:text-black",
  pricingButtonIcon: "ml-3 w-5 h-5 group-hover/btn:translate-x-1 transition-transform",
  pricingHeroSection: "flex flex-col items-center text-center space-y-8",
  pricingHeroPill: "flex items-center gap-3 px-4 py-1.5 rounded-full bg-studio/5 border border-studio/20 backdrop-blur-md",
  pricingHeroIcon: "w-4 h-4 text-studio",
  pricingHeroText: "text-[10px] font-black uppercase tracking-[0.4em] text-studio",
  pricingHeroCopy: "space-y-4",
  pricingHeroTitle: "text-5xl md:text-8xl font-black tracking-tighter text-white uppercase italic leading-none",
  pricingHeroDescription: "max-w-2xl mx-auto text-zinc-500 font-bold uppercase tracking-[0.2em] text-[11px] leading-relaxed",
  pricingFooterRow: "flex items-center gap-4",
  pricingFooterStatIconSuccess: "w-4 h-4 text-emerald-500",
  pricingFooterStatIconStudio: "w-4 h-4 text-studio",
  pricingFooterStatIconSecondary: "w-4 h-4 text-amber-500",
  nodeCardDecor: "absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity",
  nodeCardDecorIcon: "w-16 h-16 text-studio",
  contactMetaIcon: "w-3 h-3 text-zinc-700",
  hubIcon: "w-4 h-4 text-zinc-700",
  hubStatusRow: "flex items-center gap-2",
  helpCardIcon: "w-5 h-5 text-studio fill-studio",
  categoryButtonGroup: "flex flex-wrap gap-2",
  formGrid: "grid grid-cols-1 md:grid-cols-2 gap-8",
  formField: "space-y-3",
  submitSpinner: "w-4 h-4 border-2 border-zinc-500 border-t-zinc-200 rounded-full animate-spin",
  submitButtonContent: "flex items-center gap-3",
  tierGrid: "grid grid-cols-1 md:grid-cols-3 gap-10",
  cardBase: "rounded-[3rem] border transition-all duration-500 relative overflow-hidden flex flex-col group",
  cardDefault: "bg-[#0a0a0b] border-white/5 hover:border-white/10",
  cardHighlighted: "bg-studio/[0.03] border-studio shadow-[0_30px_70px_rgba(6,182,212,0.15)]",
  cardGlow: "absolute top-0 right-0 w-64 h-64 blur-[100px] rounded-full opacity-0 group-hover:opacity-20 transition-opacity",
  cardRow: "flex items-center justify-between mb-12",
  iconWrapper: "w-16 h-16 rounded-2xl flex items-center justify-center transition-all duration-500",
  iconDefault: "bg-white/[0.03] border border-white/5 text-zinc-500 group-hover:bg-white group-hover:text-black",
  iconHighlighted: "bg-studio text-black shadow-[0_0_30px_rgba(6,182,212,0.4)]",
  cardTitle: "text-3xl font-black text-white uppercase italic tracking-tighter group-hover:text-studio transition-colors",
  cardPrice: "text-5xl md:text-6xl font-black text-white italic tracking-tighter",
  cardSubtitle: "text-zinc-600 font-black uppercase tracking-[0.3em] text-[10px]",
  featureLine: "flex items-center gap-4 group/item",
  featureIcon: "w-5 h-5 rounded-lg flex items-center justify-center transition-all duration-300",
  featureText: "text-[11px] text-zinc-500 font-black uppercase tracking-widest group-hover/item:text-white transition-colors",
  featureItemHighlighted: "bg-studio/20 text-studio",
  featureItemDefault: "bg-white/5 text-zinc-600 group-hover/item:bg-white/10",
  toolbarDivider: "mb-10 pt-8 border-t border-white/5 flex items-center justify-between",
  footerStats: "mt-20 pt-12 border-t border-white/5 flex flex-col md:flex-row items-center justify-center gap-16 text-[9px] font-black text-zinc-700 uppercase tracking-[0.4em]",
  enterprisePanel: "p-12 md:p-20 rounded-[4rem] bg-[#0a0a0b] border border-white/5 flex flex-col lg:flex-row items-center justify-between gap-12 relative overflow-hidden group shadow-3xl",
  enterpriseOverlay: "absolute inset-0 bg-studio/[0.02] opacity-50 group-hover:opacity-100 transition-opacity",
  enterpriseText: "relative z-10 text-center lg:text-left space-y-6 max-w-2xl",
  enterpriseBadge: "flex items-center gap-3 justify-center lg:justify-start",
  enterpriseBadgeText: "text-[10px] font-black text-studio uppercase tracking-[0.4em]",
  enterpriseHeadingCopy: "space-y-4",
  enterpriseHeading: "text-4xl md:text-6xl font-black text-white uppercase italic tracking-tighter",
  enterpriseCopy: "text-zinc-500 text-[11px] font-bold uppercase tracking-[0.2em] leading-relaxed",
  enterpriseButton: "relative z-10 h-20 px-16 rounded-[2rem] bg-white text-black font-black uppercase tracking-[0.3em] text-[11px] hover:bg-studio hover:scale-105 transition-all shadow-2xl",
  inputCard: "bg-zinc-900/60 backdrop-blur-2xl border border-white/5 rounded-[2.5rem] p-3 pl-8 focus-within:border-studio/50 transition-all duration-500 shadow-2xl relative flex items-center",
  searchIcon: "w-6 h-6 transition-colors",
  searchInput: "bg-transparent border-none focus-visible:ring-0 text-white placeholder:text-zinc-700 text-xl py-8 font-black uppercase tracking-widest w-full",
  searchButton: "bg-studio text-black font-black uppercase tracking-widest rounded-[1.5rem] px-10 h-16 hover:bg-white transition-all shadow-[0_0_30px_rgba(6,182,212,0.3)]",
  supportGrid: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8",
  supportCard: "p-10 rounded-[3rem] bg-[#0a0a0b] border border-white/5 hover:border-studio/50 hover:shadow-[0_20px_50px_rgba(0,0,0,0.5)] transition-all duration-500 group cursor-pointer relative overflow-hidden h-full",
  supportCardOverlay: "absolute top-0 right-0 p-8 opacity-5 group-hover:opacity-10 transition-opacity pointer-events-none",
  supportCardInner: "relative z-10 space-y-10",
  supportCardIcon: "w-16 h-16 rounded-2xl bg-white/[0.03] border border-white/5 flex items-center justify-center transition-all duration-700 group-hover:bg-studio group-hover:-rotate-6",
  supportCardHeading: "text-xl font-black text-white uppercase italic tracking-widest group-hover:text-studio transition-colors",
  sectionHeaderAlt: "flex flex-col items-center text-center space-y-6",
  pageTitleAlt: "text-5xl md:text-8xl font-black text-white uppercase italic tracking-tighter",
  pageDescriptionAlt: "text-zinc-500 max-w-2xl uppercase text-[11px] font-bold tracking-[0.2em] leading-relaxed",
  nodeGrid: "grid grid-cols-1 md:grid-cols-3 gap-8",
  nodeCard: "p-8 rounded-[2.5rem] bg-[#0a0a0b] border border-white/5 hover:border-studio/30 transition-all group relative overflow-hidden",
  nodeIcon: "w-10 h-10 text-studio mb-8 group-hover:scale-110 transition-transform",
  nodeCardBody: "space-y-1",
  nodeCardLabel: "text-[10px] font-black text-zinc-500 uppercase tracking-[0.3em]",
  nodeCardValue: "text-lg font-black text-white uppercase italic",
  nodeCardMeta: "flex items-center gap-2 pt-2",
  nodeCardMetaText: "text-[9px] font-black text-zinc-600 uppercase tracking-widest",
  sectionGroup: "space-y-4",
  sectionSubtitle: "text-[10px] font-black uppercase tracking-[0.4em] text-white",
  hubList: "space-y-3",
  hubCard: "p-4 rounded-2xl bg-white/[0.02] border border-white/5 flex items-center justify-between",
  hubInfo: "flex items-center gap-3",
  hubTextGroup: "flex flex-col",
  hubLocation: "text-[10px] font-black text-white uppercase",
  hubLat: "text-[8px] font-bold text-zinc-600 tabular-nums",
  statusDot: "w-1.5 h-1.5 rounded-full animate-pulse",
  statusOptimal: "bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.5)]",
  statusWarning: "bg-amber-500",
  hubStatusText: "text-[8px] font-black text-zinc-500 uppercase tracking-widest",
  heroBadge: "inline-flex items-center gap-3 px-4 py-1.5 rounded-full bg-studio/5 border border-studio/20",
  heroBadgeText: "text-[10px] font-black text-studio uppercase tracking-[0.3em]",
  helpCardHeading: "text-xs font-black text-white uppercase tracking-widest",
  form: "space-y-10 relative z-10",
  formSection: "space-y-4",
  formSectionTitle: "text-[10px] font-black uppercase tracking-[0.4em] text-zinc-600",
  formLabel: "text-[10px] font-black text-zinc-600 uppercase tracking-[0.3em]",
  gridPanel: "grid grid-cols-1 lg:grid-cols-12 gap-16",
  sidebar: "lg:col-span-4 space-y-10",
  sidebarSticky: "space-y-6 sticky top-32",
  nodeText: "text-[10px] font-black text-white uppercase",
  nodeSub: "text-[8px] font-bold text-zinc-600 tabular-nums",
  helpCard: "p-8 rounded-[2rem] bg-studio/[0.02] border border-studio/10",
  helpCardTitle: "flex items-center gap-3 mb-4",
  helpCardText: "text-[10px] font-bold text-zinc-500 uppercase tracking-widest leading-relaxed",
  formPanel: "lg:col-span-8 bg-[#0a0a0b] border border-white/5 rounded-[3rem] p-8 md:p-16 shadow-2xl relative overflow-hidden group",
  formOverlay: "absolute top-0 right-0 w-64 h-64 bg-studio/5 blur-3xl opacity-0 group-hover:opacity-100 transition-opacity",
  formInput: "w-full bg-black/50 border-zinc-800 rounded-2xl h-14 font-black uppercase tracking-widest text-[11px] focus:border-studio/50",
  categoryButton: "px-4 py-2 rounded-xl text-[9px] font-black uppercase tracking-widest border transition-all",
  categoryActive: "bg-studio text-black border-studio",
  categoryInactive: "bg-zinc-900 border-zinc-800 text-zinc-500 hover:text-zinc-300",
  textarea: "w-full bg-black/50 border border-zinc-800 rounded-[2rem] px-6 py-5 text-[11px] font-black uppercase tracking-widest text-white focus:outline-none focus:border-studio/50 transition-all resize-none",
  submitButton: "w-full h-20 rounded-[2rem] font-black uppercase tracking-[0.3em] text-xs transition-all relative overflow-hidden group",
  submitButtonActive: "bg-studio text-black hover:bg-white hover:scale-[1.02] shadow-[0_20px_50px_rgba(6,182,212,0.3)]",
  submitButtonDisabled: "bg-zinc-800 text-zinc-500",
  termsRoot: "min-h-screen bg-[#050505] text-zinc-100 py-32 px-6 relative overflow-hidden",
  termsWrapper: "max-w-7xl mx-auto space-y-24 relative z-10",
  termsHeader: "flex flex-col items-center text-center space-y-8",
  termsIndex: "lg:col-span-4 space-y-10",
  termsIndexCard: "space-y-2 sticky top-32",
  termsIndexBadge: "p-2.5 bg-studio/10 rounded-xl border border-studio/20",
  termsSection: "p-10 md:p-16 rounded-[3rem] bg-[#0a0a0b] border border-white/5 space-y-10 group relative overflow-hidden",
  termsSectionFooter: "p-12 md:p-20 rounded-[4rem] bg-studio/[0.03] border border-studio/20 text-center space-y-10 relative overflow-hidden group",
  termsFooter: "mt-20 pt-12 border-t border-white/5 flex flex-col md:flex-row items-center justify-between gap-8 text-[9px] font-black text-zinc-700 uppercase tracking-[0.4em]",
  protocolAcceptButton: "relative z-10 h-20 px-16 rounded-[2rem] bg-studio text-black font-black uppercase tracking-[0.3em] text-[11px] hover:bg-white hover:scale-105 transition-all shadow-[0_30px_70px_rgba(6,182,212,0.3)]",
};