/**
 * Rules registry for validation engine.
 * This file contains enumerations or simple helpers for rule identifiers.
 */
export const RULES = {
  FORMAT_SECTION_MISSING: 'FORMAT_SECTION_MISSING',
  TITLE_COUNT: 'TITLE_COUNT',
  TAG_COUNT: 'TAG_COUNT',
  SCENE_FIELD_MISSING: 'SCENE_FIELD_MISSING',
  EMPTY_RESPONSE: 'EMPTY_RESPONSE',
  JSON_PARSE_ERROR: 'JSON_PARSE_ERROR',
  NOT_AN_ARRAY: 'NOT_AN_ARRAY',
  EMPTY_ARRAY: 'EMPTY_ARRAY',
  TITLE_SECTION: 'TITLE_SECTION',
  TAGS_SECTION: 'TAGS_SECTION',
  SCENE_JSON_KEY_MISSING: 'SCENE_JSON_KEY_MISSING',
  VIDEO_SCRIPT_TOO_SHORT: 'VIDEO_SCRIPT_TOO_SHORT',
  INVALID_CONTENT_TYPE: 'INVALID_CONTENT_TYPE',
  VIDEO_PROMPT_GENERATION_FAILED: 'VIDEO_PROMPT_GENERATION_FAILED',
  VIDEO_RENDER_FAILED: 'VIDEO_RENDER_FAILED'
} as const;

export type RuleKey = keyof typeof RULES;

export default RULES;
