export const templateStyles = {
  grid: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10",
  card: "h-[550px] bg-[#050505] border border-white/5 transition-all duration-700 overflow-hidden flex flex-col relative rounded-[2.5rem] shadow-2xl",
  cardHover: "hover:border-studio/30 hover:shadow-[0_0_80px_rgba(6,182,212,0.1)] hover:-translate-y-2",
  thumbnailBox: "relative h-56 overflow-hidden",
  thumbnailImg: "w-full h-full object-cover grayscale opacity-30 transition-all duration-1000 group-hover:grayscale-0 group-hover:opacity-60 group-hover:scale-110",
  iconBox: "w-12 h-12 rounded-2xl flex items-center justify-center border shadow-2xl transition-all duration-500 group-hover:scale-110 group-hover:rotate-12",
  badge: "text-[8px] font-black uppercase tracking-[0.2em] px-3 py-1.5 border-none shadow-2xl rounded-full backdrop-blur-md",
  title: "text-2xl font-black uppercase tracking-tighter text-white transition-colors leading-none mb-2 group-hover:text-studio",
  vibe: "text-[9px] font-black text-zinc-500 uppercase tracking-[0.2em] leading-none mb-6",
  elementTag: "text-[7px] font-black uppercase px-2.5 py-1 bg-white/[0.03] border border-white/5 text-zinc-500 rounded-lg italic transition-all group-hover:border-studio/30 group-hover:text-studio/80",
  readyRow: "flex items-center gap-2",
  readyDot: "w-1.5 h-1.5 rounded-full bg-studio animate-pulse",
  readyText: "text-[7px] font-black text-zinc-500 uppercase tracking-widest",
  cardMetaBox: "w-10 h-10 rounded-xl flex items-center justify-center border border-white/5 bg-white/[0.02] shadow-2xl transition-all duration-500 group-hover:border-studio/30 group-hover:bg-studio/5",
  cardMoreText: "text-[7px] font-black text-zinc-700 flex items-center",
  detailsButton: "w-full text-[8px] text-zinc-600 hover:text-studio uppercase tracking-[0.3em] font-black py-2 transition-all flex items-center justify-center gap-2",
  statBox: "p-3 rounded-2xl bg-white/[0.02] border border-white/5 flex items-center gap-3 transition-colors group-hover:bg-white/[0.04]",
  statLabel: "text-[7px] text-zinc-600 font-black uppercase tracking-widest leading-none",
  statValue: "text-[10px] font-mono font-bold leading-none mt-1",
  deployBtn: "w-full h-14 bg-white text-black hover:bg-studio hover:text-white text-[10px] font-black uppercase tracking-[0.3em] transition-all relative overflow-hidden shadow-2xl active:scale-95 rounded-2xl border-none",
  modalOverlay: "absolute inset-0 bg-black/80 backdrop-blur-sm",
  modalContent: "relative z-10 w-full max-w-6xl h-[90vh] bg-[#050505] border border-white/5 rounded-[2.5rem] overflow-hidden shadow-2xl grid grid-cols-1 lg:grid-cols-[1.05fr_1fr]",
  modalCloseBtn: "absolute top-6 right-6 z-30 w-12 h-12 rounded-full bg-black/60 border border-white/10 text-white hover:text-studio hover:border-studio/40 transition-all flex items-center justify-center backdrop-blur-md",
  modalVisualSide: "relative min-h-[280px] lg:min-h-full overflow-hidden bg-zinc-950",
  modalContentSide: "relative flex flex-col gap-8 p-8 lg:p-12 overflow-y-auto bg-[#050505]",
  modalSectionTitle: "text-[11px] font-black text-white uppercase tracking-[0.2em] flex items-center gap-2",
  modalInfoCard: "rounded-2xl border border-white/5 bg-white/[0.02] p-4 flex items-center justify-between gap-3 shadow-2xl transition-colors hover:bg-white/[0.04]",
  modalDetailRow: "flex items-center justify-between gap-4 rounded-xl border border-white/5 bg-white/[0.02] px-4 py-3",
  modalPromptBox: "rounded-[2rem] border border-white/5 bg-white/[0.02] p-6 shadow-2xl",
  modalPromptText: "text-sm leading-relaxed text-zinc-300 font-mono whitespace-pre-wrap",
  structureContainer: "bg-[#050505] border border-white/5 shadow-2xl overflow-hidden min-h-[700px] relative rounded-[3rem]",
  structureHeader: "p-8 md:p-12 border-b border-white/5 bg-gradient-to-br from-white/[0.03] to-transparent relative z-10 flex flex-col md:flex-row md:items-center justify-between gap-8",
  structureTitle: "text-2xl md:text-3xl font-black uppercase tracking-tighter text-white",
  structureSubtitle: "text-[10px] uppercase tracking-[0.4em] text-zinc-500 font-black",
  structureBadge: "text-[9px] uppercase tracking-[0.3em] font-black bg-cyan-500/10 text-cyan-400 border-cyan-500/20 rounded-full px-4 py-2",
  structureVerifiedBadge: "text-[9px] uppercase tracking-[0.3em] font-black bg-emerald-500/10 text-emerald-400 border-emerald-500/20 rounded-full px-4 py-2",
  structureProse: "prose prose-invert max-w-none prose-p:text-zinc-300 prose-headings:text-white prose-strong:text-white prose-a:text-cyan-400 prose-code:text-cyan-300",
  vaultContainer: "flex flex-col items-center justify-center min-h-[600px] space-y-10 bg-[#020202] border border-white/5 rounded-[3rem] text-center relative overflow-hidden group",
  vaultIconCircle: "w-40 h-40 rounded-full bg-studio/5 flex items-center justify-center border border-studio/10 shadow-[0_0_50px_rgba(6,182,212,0.1)] transition-all duration-1000 relative group-hover:scale-105 after:content-[''] after:absolute after:inset-0 after:rounded-full after:border after:border-studio/20 after:animate-ping after:opacity-20",
  vaultBadge: "inline-block px-5 py-2 bg-studio/10 border border-studio/20 rounded-full text-[9px] uppercase tracking-[0.4em] text-studio font-black mb-4",
  vaultTitle: "text-5xl font-black text-white uppercase tracking-tighter italic leading-none",
  vaultDesc: "text-[11px] text-zinc-500 font-medium leading-relaxed tracking-wider max-w-sm",
  vaultBtn: "bg-studio text-black hover:bg-white font-black uppercase tracking-[0.3em] h-16 px-14 rounded-2xl shadow-[0_0_40px_rgba(6,182,212,0.2)] active:scale-95 transition-all",
  scrollbar: "engine-scrollbar"
};
