export const landingStyles = {
  page: "min-h-screen bg-[#030303] text-zinc-100 selection:bg-studio/30 selection:text-studio overflow-x-hidden relative",
  pageGridOverlay: "absolute inset-0 pointer-events-none overflow-hidden z-0",
  gridBackground: "absolute inset-0 bg-[linear-gradient(to_right,#ffffff03_1px,transparent_1px),linear-gradient(to_bottom,#ffffff03_1px,transparent_1px)] bg-[size:40px_40px]",
  decorTop: "absolute top-0 left-[10%] w-[1000px] h-[1000px] bg-studio/5 rounded-full blur-[120px] pointer-events-none",
  decorBottom: "absolute top-[20%] right-[-10%] w-[800px] h-[800px] bg-purple-500/5 rounded-full blur-[150px] pointer-events-none",
  header: "fixed top-0 left-0 right-0 z-[100] border-b border-white/5 bg-black/80",
  nav: "max-w-7xl mx-auto px-6 h-20 flex items-center justify-between",
  navBrand: "flex items-center gap-3 no-underline group",
  brandText: "text-xl font-black tracking-tighter uppercase text-white",
  brandAccent: "text-studio",
  navLinks: "hidden lg:flex items-center gap-2",
  navLink: "px-4 py-2 text-sm font-medium text-zinc-400 hover:text-white transition-colors no-underline",
  navActions: "flex items-center gap-4",
  navLogin: "px-5 py-2 text-sm font-bold text-zinc-400 hover:text-white transition-colors hidden sm:block",
  navSignupButton: "bg-white text-black hover:bg-zinc-200 font-bold rounded-full px-6 transition-all transform hover:scale-105",
  mobileToggle: "lg:hidden p-2 text-zinc-400",
  heroSection: "pt-40 pb-20 px-6 relative z-10",
  heroContent: "max-w-7xl mx-auto text-center space-y-12",
  heroBadge: "inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-studio/10 border border-studio/20",
  heroBadgeText: "text-xs font-black uppercase tracking-[0.3em] text-studio-glow",
  heroTitle: "text-2xl md:text-3xl lg:text-4xl font-black tracking-tight leading-[1.1] text-white relative",
  heroGradientText: "text-transparent bg-clip-text bg-gradient-to-r from-studio via-purple-500 to-studio drop-shadow-[0_0_10px_rgba(6,182,212,0.3)] relative z-10",
  heroSubtitle: "max-w-xl mx-auto text-zinc-500 text-base md:text-lg font-medium leading-relaxed tracking-wide",
  heroActions: "flex flex-col sm:flex-row items-center justify-center gap-6 pt-4",
  actionPrimary: "h-16 px-10 rounded-2xl bg-studio text-black hover:bg-studio/90 font-black uppercase tracking-widest text-sm shadow-[0_0_30px_rgba(6,182,212,0.3)] transition-all hover:scale-105 active:scale-95",
  actionSecondary: "h-16 px-10 rounded-2xl border-white/10 bg-white/5 hover:bg-white/10 text-white font-black uppercase tracking-widest text-sm transition-all",
  videoSection: "max-w-5xl mx-auto py-16",
  videoCard: "relative rounded-3xl overflow-hidden border border-white/10 shadow-[0_0_50px_rgba(6,182,212,0.15)] group",
  videoLabel: "absolute top-4 left-4 z-20 flex items-center gap-2 bg-black/60 backdrop-blur-md px-3 py-1.5 rounded-full border border-white/10",
  videoLabelText: "text-xs font-bold text-white uppercase tracking-wider",
  videoOverlay: "absolute inset-0 bg-black/40 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 z-10",
  videoPlayButton: "w-20 h-20 rounded-full bg-studio text-black hover:scale-110 transition-transform shadow-[0_0_30px_rgba(6,182,212,0.5)] flex items-center justify-center",
  sectionBlock: "max-w-7xl mx-auto py-20",
  sectionTitle: "text-2xl font-black text-center text-white uppercase tracking-wider mb-12",
  sectionBlockCenter: "max-w-7xl mx-auto py-20 text-center",
  sectionText: "text-zinc-400 mb-6 max-w-xl mx-auto",
  pricingActionButton: "h-14 px-12 rounded-2xl bg-studio text-black font-black uppercase tracking-widest hover:bg-studio/90 transition-all hover:scale-105",
  faqHeading: "text-2xl font-black text-center text-white uppercase tracking-wider mb-12",
  faqGroup: "space-y-4 max-w-3xl mx-auto",
  faqItem: "bg-zinc-900/40 rounded-2xl p-6 border border-white/5 hover:border-white/10 transition-all group",
  featureGrid: "grid grid-cols-1 md:grid-cols-3 gap-12",
  featureCard: "flex flex-col items-center text-center p-8 rounded-3xl bg-zinc-900/40 border border-white/5 hover:border-studio/30 hover:-translate-y-2 hover:shadow-[0_15px_30px_rgba(0,0,0,0.5)] transition-all duration-300 group will-change-transform",
  featureIcon: "w-16 h-16 rounded-2xl bg-studio/10 flex items-center justify-center mb-6 group-hover:bg-studio/20 group-hover:scale-110 transition-all",
  faqSummary: "text-white font-bold cursor-pointer flex items-center justify-between",
  faqDesc: "text-zinc-400 mt-4 leading-relaxed",
};
