import React from 'react';
import { 
  Compass, 
  TrendingUp, 
  Users, 
  MessageSquare, 
  Heart,
  Share2,
  Play
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { motion } from 'motion/react';

const trendingScripts = [
  { id: 1, title: 'The Last Samurai of Neo-Tokyo', author: 'AnimeMaster', likes: 1200, comments: 45, genre: 'Cyberpunk' },
  { id: 2, title: 'Reincarnated as a Vending Machine', author: 'IsekaiKing', likes: 850, comments: 120, genre: 'Comedy' },
  { id: 3, title: 'Shadow Realm Chronicles', author: 'DarkWriter', likes: 2100, comments: 89, genre: 'Dark Fantasy' },
];

export function CommunityPage() {
  return (
    <div className="p-8 max-w-7xl mx-auto space-y-12">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div className="space-y-2">
          <h1 className="text-4xl font-black tracking-tighter flex items-center gap-3">
            <Compass className="w-10 h-10 text-red-600" />
            DISCOVER
          </h1>
          <p className="text-zinc-500 text-lg">Explore scripts generated by the global anime community.</p>
        </div>
        <div className="flex items-center gap-4">
          <Button className="bg-red-600 hover:bg-red-700">
            <Share2 className="w-4 h-4 mr-2" />
            Share Your Script
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-8">
          <div className="flex items-center justify-between">
            <h2 className="text-xl font-bold flex items-center gap-2">
              <TrendingUp className="w-5 h-5 text-red-500" />
              Trending Now
            </h2>
            <Button variant="link" className="text-red-500">View All</Button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {trendingScripts.map((script, idx) => (
              <motion.div
                key={script.id}
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: idx * 0.1 }}
              >
                <Card className="bg-zinc-900/50 border-zinc-800 overflow-hidden group cursor-pointer hover:border-red-500/50 transition-all">
                  <div className="aspect-video bg-zinc-950 relative">
                    <img 
                      src={`https://picsum.photos/seed/community-${script.id}/800/450`} 
                      alt={script.title}
                      className="w-full h-full object-cover opacity-50 group-hover:scale-105 transition-transform duration-700"
                      referrerPolicy="no-referrer"
                    />
                    <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                      <div className="w-12 h-12 bg-red-600 rounded-full flex items-center justify-center shadow-xl">
                        <Play className="w-6 h-6 fill-white text-white ml-1" />
                      </div>
                    </div>
                  </div>
                  <CardHeader className="p-4">
                    <div className="flex items-center gap-2 mb-2">
                      <span className="text-[10px] font-bold uppercase tracking-widest text-red-500 px-2 py-0.5 bg-red-500/10 rounded">
                        {script.genre}
                      </span>
                    </div>
                    <CardTitle className="text-base leading-tight">{script.title}</CardTitle>
                    <CardDescription className="text-[10px] flex items-center gap-1">
                      by <span className="text-zinc-300">{script.author}</span>
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="p-4 pt-0 flex items-center gap-4 text-zinc-500">
                    <div className="flex items-center gap-1 text-[10px]">
                      <Heart className="w-3 h-3" />
                      {script.likes}
                    </div>
                    <div className="flex items-center gap-1 text-[10px]">
                      <MessageSquare className="w-3 h-3" />
                      {script.comments}
                    </div>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>

        <div className="space-y-8">
          <h2 className="text-xl font-bold flex items-center gap-2">
            <Users className="w-5 h-5 text-red-500" />
            Top Creators
          </h2>
          <div className="space-y-4">
            {[1, 2, 3, 4, 5].map((i) => (
              <div key={i} className="flex items-center justify-between p-4 bg-zinc-900/30 border border-zinc-800 rounded-xl hover:bg-zinc-800/50 transition-colors cursor-pointer">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full bg-zinc-800 border border-zinc-700 overflow-hidden">
                    <img src={`https://i.pravatar.cc/150?u=${i}`} alt="Avatar" referrerPolicy="no-referrer" />
                  </div>
                  <div>
                    <p className="text-sm font-bold">Creator_{i}</p>
                    <p className="text-[10px] text-zinc-500">42 Scripts • 1.2k Followers</p>
                  </div>
                </div>
                <Button variant="ghost" size="sm" className="text-red-500 hover:text-red-400 hover:bg-transparent">Follow</Button>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
