export const worldStyles = {
  container: "world-container",
  header: "world-header",
  headerTitle: "world-header-title",
  grid: "world-grid",
  textarea: "world-textarea",
  contentArea: "world-content-area",
  mainColumn: "world-main-column",
  sidebar: "world-sidebar",
  badge: "world-badge",
  badgeText: "world-badge-text",
  prose: "world-prose",
  actionButton: "flex items-center gap-2 px-5 py-2.5 bg-white text-black hover:bg-zinc-200 rounded-full transition-all group disabled:opacity-50",
  actionButtonGhost: "flex items-center gap-2 px-5 py-2.5 bg-white/5 hover:bg-white/10 border border-white/10 rounded-full transition-all group",
  sidebarCard: "p-6 bg-[#050505] border border-white/5 rounded-[2rem] space-y-4 relative overflow-hidden group",
  sidebarGlow: "absolute inset-0 blur-[40px] pointer-events-none transition-all duration-700",
  sidebarContent: "relative z-10 space-y-4",
  sidebarTitle: "text-[10px] font-black text-zinc-500 uppercase tracking-widest flex items-center gap-2",
  sidebarPromptInput: "w-full bg-black/40 border border-white/5 rounded-xl p-3 text-[10px] font-medium text-zinc-300 placeholder:text-zinc-700 focus:outline-none focus:border-white/10 transition-colors min-h-[100px] resize-none overflow-hidden",
  sidebarPromptBox: "p-4 bg-black/40 border border-white/5 rounded-xl",
  sidebarPromptText: "text-[9px] font-medium text-zinc-500 leading-relaxed italic",
  sidebarNote: "text-[8px] text-zinc-600 font-bold uppercase tracking-tighter leading-relaxed",
  statCard: "p-6 bg-[#050505] border border-white/5 rounded-[2rem] space-y-4 relative group overflow-hidden hover:border-white/10 transition-all",
  statIconBox: "w-10 h-10 rounded-xl bg-white/[0.03] border border-white/10 flex items-center justify-center group-hover:scale-110 transition-transform",
  statLabel: "text-[10px] font-black text-zinc-500 uppercase tracking-widest",
  statValue: "text-sm font-black text-white uppercase tracking-tighter line-clamp-1"
};
