import type { AIModel } from '../aiModels';

export const TEXT_MODELS: AIModel[] = [
  { id: 'gemini-3.1-flash-lite', name: 'Gemini 3.1 Flash Lite', category: 'text', capabilities: ['text-out'], description: 'Lightweight Gemini text model (fast, high-throughput)', isFree: true },
  { id: 'gemini-2.5-flash', name: 'Gemini 2.5 Flash', category: 'text', capabilities: ['text-out'], description: 'Gemini 2.5 Flash text model', isFree: true },
  { id: 'gemini-2.5-pro', name: 'Gemini 2.5 Pro', category: 'text', capabilities: ['text-out'], description: 'Gemini 2.5 Pro text model', isFree: false },
  { id: 'gemini-2-flash', name: 'Gemini 2 Flash', category: 'text', capabilities: ['text-out'], description: 'Gemini 2 Flash text core', isFree: true },
  { id: 'gemini-2-flash-lite', name: 'Gemini 2 Flash Lite', category: 'text', capabilities: ['text-out'], description: 'Gemini 2 Flash Lite text core', isFree: true },
  { id: 'gemini-3-flash', name: 'Gemini 3 Flash', category: 'text', capabilities: ['text-out'], description: 'Gemini 3 Flash standard', isFree: true },
  { id: 'gemini-3.5-flash', name: 'Gemini 3.5 Flash', category: 'text', capabilities: ['text-out'], description: 'Gemini 3.5 Flash preview', isFree: true },
  { id: 'gemini-3.1-pro', name: 'Gemini 3.1 Pro', category: 'text', capabilities: ['text-out'], description: 'Gemini 3.1 Pro advanced reasoning', isFree: false },
  { id: 'gemini-2.5-flash-lite', name: 'Gemini 2.5 Flash Lite', category: 'text', capabilities: ['text-out'], description: 'Gemini 2.5 Flash Lite core', isFree: true },
  { id: 'gpt-4o', name: 'OpenAI GPT-4o', category: 'text', capabilities: ['text-out'], description: 'Flagship high-intelligence multimodal model', isFree: false },
  { id: 'gpt-4o-mini', name: 'OpenAI GPT-4o Mini', category: 'text', capabilities: ['text-out'], description: 'Fast, lightweight, and cost-effective OpenAI model', isFree: true },
  { id: 'gpt-4-turbo', name: 'OpenAI GPT-4 Turbo', category: 'text', capabilities: ['text-out'], description: 'Legacy OpenAI flagship agent model', isFree: false },
  { id: 'o1-preview', name: 'OpenAI o1 Preview', category: 'text', capabilities: ['text-out'], description: 'Advanced reasoning and complex logic model', isFree: false },
  { id: 'o1-mini', name: 'OpenAI o1 Mini', category: 'text', capabilities: ['text-out'], description: 'Lightweight reasoning-focused model', isFree: false },
  { id: 'llama-3.1-8b-instant', name: 'Llama 3.1 (Meta)', category: 'text', capabilities: ['text-out'], description: 'Meta Llama 3.1 lightweight free-tier model', isFree: true },
  { id: 'mistral-large-2', name: 'Mistral Large 2', category: 'text', capabilities: ['text-out'], description: 'Mistral Large 2 free-tier listing', isFree: true },
  { id: 'gemma-2-27b-it', name: 'Gemma 2 (Google)', category: 'text', capabilities: ['text-out'], description: 'Gemma 2 instruction-tuned model', isFree: true },
  { id: 'phi-3.5-mini-instruct', name: 'Phi-3.5-mini', category: 'text', capabilities: ['text-out'], description: 'Phi-3.5-mini instruction model', isFree: true },
  { id: 'qwen-2.5-72b-instruct', name: 'Qwen 2.5', category: 'text', capabilities: ['text-out'], description: 'Qwen 2.5 instruction model', isFree: true },
  { id: 'falcon-2-11b-instruct', name: 'Falcon 2', category: 'text', capabilities: ['text-out'], description: 'Falcon 2 instruction model', isFree: true },
  { id: 'deepseek-v2.5', name: 'DeepSeek-V2.5', category: 'text', capabilities: ['text-out'], description: 'DeepSeek-V2.5 text model', isFree: true },
  { id: 'jamba', name: 'Jamba', category: 'text', capabilities: ['text-out'], description: 'Jamba hybrid language model', isFree: true },
  { id: 'nemotron-3', name: 'Nemotron-3', category: 'text', capabilities: ['text-out'], description: 'Nemotron-3 open model', isFree: true },
  { id: 'internlm-2.5', name: 'InternLM 2.5', category: 'text', capabilities: ['text-out'], description: 'InternLM 2.5 chat model', isFree: true },
  { id: 'command-r-plus', name: 'Command R+', category: 'text', capabilities: ['text-out'], description: 'Command R+ retrieval model', isFree: true },
  { id: 'deepseek-coder-v2', name: 'DeepSeek-Coder-V2', category: 'text', capabilities: ['code'], description: 'DeepSeek-Coder-V2 coding model', isFree: true },
  { id: 'codeqwen-1.5', name: 'CodeQwen 1.5', category: 'text', capabilities: ['code'], description: 'CodeQwen 1.5 coding model', isFree: true },
  { id: 'starcoder2', name: 'StarCoder2', category: 'text', capabilities: ['code'], description: 'StarCoder2 code model', isFree: true },
  { id: 'florence-2', name: 'Florence-2', category: 'other', capabilities: ['vision'], description: 'Florence-2 vision-language model', isFree: true },
  { id: 'paligemma', name: 'PaliGemma', category: 'other', capabilities: ['vision'], description: 'PaliGemma vision-language model', isFree: true },
  { id: 'llava-v1.6', name: 'LLaVA-v1.6', category: 'other', capabilities: ['vision'], description: 'LLaVA-v1.6 multimodal model', isFree: true },
  { id: 'minicpm-v', name: 'MiniCPM-V', category: 'other', capabilities: ['vision'], description: 'MiniCPM-V multimodal model', isFree: true },
];

export default TEXT_MODELS;